version: '3.7'

networks:
  network:
    driver: bridge

services:
  nn_drugs_predictor:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nn_drugs_predictor
    ports:
      - '5000:5000'
    expose:
      - 5000
    networks:
      - network
